language: scala
sudo: required

services:
  - docker

script:

  # install mill
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.2.0/0.2.0 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH

  # run tests
  - mill all _.test
